services:
  - type: web
    name: whatnow-frontend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
